import type { 
  AppointmentWithDetails, 
  Service, 
  Staff, 
  Profile, 
  Reward, 
  LoyaltyTransaction,
  AvailabilitySetting,
  BlockedDate
} from '../types';
import { format, subDays, addDays } from 'date-fns';

// 1. SERVICES MOCK (Incluant les 4 modèles signatures de tresses & braids)
export const MOCK_SERVICES: Service[] = [
  {
    id: 'srv-braid-1',
    name: 'Stitch braid with cross',
    description: 'Tresses stitch haute précision avec motif géométrique en croix sur le dessus. Tracés nets et finitions soignées.',
    duration_minutes: 150, // 2h - 3h
    price: 50,
    category: 'Tresses & Braids',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'srv-braid-2',
    name: 'Stitch braids',
    description: 'Tresses stitch droites et soignées avec séparations nettes et contours impeccables. Confort et tenue longue durée.',
    duration_minutes: 105, // 1h30 - 2h
    price: 60,
    category: 'Tresses & Braids',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'srv-braid-3',
    name: 'Knotless braids',
    description: 'Longues tresses sans nœuds fluides et ultra-légères. Mèches rouge vif dégradées, aucune traction sur le cuir chevelu.',
    duration_minutes: 195, // 3h - 3h30
    price: 95,
    category: 'Tresses & Braids',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'srv-braid-4',
    name: 'Cornrows',
    description: 'Tresses plaquées traditionnelles régulières avec finitions attachées en chignons élégants à l’arrière de la tête.',
    duration_minutes: 90, // 1h - 2h
    price: 45,
    category: 'Tresses & Braids',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'srv-5',
    name: 'Coupe Femme & Brushing',
    description: 'Diagnostic personnalisé, shampoing traitant, coupe sur-mesure et brushing éclat haute tenue.',
    duration_minutes: 60,
    price: 45,
    category: 'Femme',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'srv-6',
    name: 'Coupe Homme & Soin Barbe',
    description: 'Coupe aux ciseaux et tondeuse, finitions rasoir, taille de barbe et serviette chaude.',
    duration_minutes: 45,
    price: 30,
    category: 'Homme',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'srv-7',
    name: 'Balayage Signature & Patine',
    description: 'Éclaircissement naturel sur-mesure avec patine neutralisante et masque reconstructeur.',
    duration_minutes: 120,
    price: 95,
    category: 'Technique',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'srv-8',
    name: 'Soin Botox Capillaire & Massage',
    description: 'Soin reconstructeur profond à la kératine et acide hyaluronique pour un effet miroir.',
    duration_minutes: 60,
    price: 55,
    category: 'Soin',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
];

// 2. STAFF MOCK (Cindy Malorie)
export const MOCK_STAFF: Staff[] = [
  {
    id: 'staff-cindy',
    user_id: 'user-cindy',
    full_name: 'Cindy Malorie',
    specialty: 'Spécialiste Braids, Tresses Artistiques & Soins Capillaires',
    bio: 'Artisan coiffeuse styliste à Pavia (Via Francana 10) et à domicile en Lombardie. Plus de 100K abonnés sur TikTok (@cindymalorie).',
    avatar_url: '/images/hairstyles/stitch-braid-cross.png',
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
];

// 3. CLIENTS PROFILES MOCK
export const MOCK_CLIENTS: Profile[] = [
  {
    id: 'client-1',
    full_name: 'Matteo Gambino',
    email: 'matteo.gambino@gmail.com',
    phone: '+39 340 1234567',
    role: 'client',
    address: 'Via Roma 12, Pavia (Italie)',
    avatar_url: null,
    loyalty_points: 120,
    preferences: {
      favorite_cut: 'Stitch braid with cross',
      hair_type: 'Crépu / Frisé 4C',
      admin_notes: 'Client très ponctuel. Préfère les finitions tondeuse sans alcool.',
    },
    created_at: '2026-01-10T14:20:00Z',
    updated_at: '2026-02-15T11:00:00Z',
  },
  {
    id: 'client-2',
    full_name: 'Chiara Bellini',
    email: 'chiara.bellini@yahoo.it',
    phone: '+39 349 7654321',
    role: 'client',
    address: 'Corso Garibaldi 45, Pavia (Italie)',
    avatar_url: null,
    loyalty_points: 285,
    preferences: {
      favorite_cut: 'Knotless braids',
      favorite_color: 'Mèches Rouge Vif',
      hair_type: 'Bouclé 3B',
      admin_notes: 'Cliente fidèle VIP. Adore les coiffures protectrices longues.',
    },
    created_at: '2026-01-05T09:15:00Z',
    updated_at: '2026-02-20T16:40:00Z',
  },
  {
    id: 'client-3',
    full_name: 'Lorenzo Rossi',
    email: 'lorenzo.rossi@outlook.it',
    phone: '+39 338 9876543',
    role: 'client',
    address: 'Via Milano 8, Pavia (Italie)',
    avatar_url: null,
    loyalty_points: 90,
    preferences: {
      favorite_cut: 'Cornrows',
      hair_type: 'Frisé 4A',
      admin_notes: 'Demande souvent des créneaux en début de matinée.',
    },
    created_at: '2026-01-18T16:00:00Z',
    updated_at: '2026-02-10T10:30:00Z',
  },
  {
    id: 'client-4',
    full_name: 'Sofia Conti',
    email: 'sofia.conti@gmail.com',
    phone: '+39 333 4567890',
    role: 'client',
    address: 'Via Torino 22, Milano (Italie)',
    avatar_url: null,
    loyalty_points: 0,
    preferences: {
      favorite_cut: 'Balayage Signature & Patine',
      favorite_color: 'Miel Doré',
      hair_type: 'Ondulé 2C',
      admin_notes: 'A découvert Cindy sur TikTok (@cindymalorie). Première prise de contact.',
    },
    created_at: '2026-02-22T18:30:00Z',
    updated_at: '2026-02-22T18:30:00Z',
  },
  {
    id: 'client-5',
    full_name: 'Alessandro Ferrari',
    email: 'a.ferrari@libero.it',
    phone: '+39 320 8765432',
    role: 'client',
    address: 'Viale Libertà 15, Pavia (Italie)',
    avatar_url: null,
    loyalty_points: 30,
    preferences: {
      favorite_cut: 'Coupe Homme & Soin Barbe',
      hair_type: 'Lisse',
      admin_notes: 'Dernier RDV il y a 3 mois.',
    },
    created_at: '2025-11-12T11:00:00Z',
    updated_at: '2025-11-20T12:00:00Z',
  },
  {
    id: 'client-6',
    full_name: 'Elena Moretti',
    email: 'elena.moretti@gmail.com',
    phone: '+39 347 1122334',
    role: 'client',
    address: 'Via Francana 8, Pavia (Italie)',
    avatar_url: null,
    loyalty_points: 350,
    preferences: {
      favorite_cut: 'Soin Botox Capillaire & Massage',
      hair_type: 'Coloré / Sensibilisé',
      admin_notes: 'Voisine du studio au 10 Via Francana. Cliente très régulière.',
    },
    created_at: '2025-10-01T15:00:00Z',
    updated_at: '2026-02-18T14:15:00Z',
  },
];

const todayStr = format(new Date(), 'yyyy-MM-dd');
const tomorrowStr = format(addDays(new Date(), 1), 'yyyy-MM-dd');
const in3DaysStr = format(addDays(new Date(), 3), 'yyyy-MM-dd');
const in5DaysStr = format(addDays(new Date(), 5), 'yyyy-MM-dd');
const yesterdayStr = format(subDays(new Date(), 1), 'yyyy-MM-dd');
const lastWeekStr = format(subDays(new Date(), 7), 'yyyy-MM-dd');
const twoWeeksAgoStr = format(subDays(new Date(), 14), 'yyyy-MM-dd');

// 4. APPOINTMENTS MOCK
export const MOCK_APPOINTMENTS: AppointmentWithDetails[] = [
  {
    id: 'app-1',
    client_id: 'client-1',
    service_id: 'srv-braid-1',
    staff_id: 'staff-cindy',
    appointment_date: todayStr,
    start_time: '10:00:00',
    end_time: '12:30:00',
    status: 'confirmed',
    location_type: 'salon',
    location_address: 'Via Francana 10, Pavia (Italie)',
    notes: 'Motif croix bien centré sur le dessus de la tête.',
    confirmation_sent: true,
    reminder_sent: true,
    reminder_scheduled_at: null,
    created_at: format(subDays(new Date(), 2), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(new Date(), 2), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[0],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[0],
  },
  {
    id: 'app-2',
    client_id: 'client-2',
    service_id: 'srv-braid-3',
    staff_id: 'staff-cindy',
    appointment_date: tomorrowStr,
    start_time: '14:00:00',
    end_time: '17:15:00',
    status: 'confirmed',
    location_type: 'home',
    location_address: 'Corso Garibaldi 45, Pavia (Italie)',
    notes: 'Apporter mèches rouges dégradées supplémentaires.',
    confirmation_sent: true,
    reminder_sent: false,
    reminder_scheduled_at: null,
    created_at: format(subDays(new Date(), 3), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(new Date(), 3), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[2],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[1],
  },
  {
    id: 'app-3',
    client_id: 'client-3',
    service_id: 'srv-braid-4',
    staff_id: 'staff-cindy',
    appointment_date: in3DaysStr,
    start_time: '09:30:00',
    end_time: '11:00:00',
    status: 'pending',
    location_type: 'salon',
    location_address: 'Via Francana 10, Pavia (Italie)',
    notes: 'Réservation en ligne à valider.',
    confirmation_sent: false,
    reminder_sent: false,
    reminder_scheduled_at: null,
    created_at: format(new Date(), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(new Date(), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[3],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[2],
  },
  {
    id: 'app-4',
    client_id: 'client-4',
    service_id: 'srv-7',
    staff_id: 'staff-cindy',
    appointment_date: in5DaysStr,
    start_time: '15:00:00',
    end_time: '17:00:00',
    status: 'pending',
    location_type: 'home',
    location_address: 'Via Torino 22, Milano (Italie)',
    notes: 'Déplacement à Milan. Diagnostic balayage préalable sur photo.',
    confirmation_sent: false,
    reminder_sent: false,
    reminder_scheduled_at: null,
    created_at: format(new Date(), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(new Date(), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[6],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[3],
  },
  {
    id: 'app-5',
    client_id: 'client-6',
    service_id: 'srv-8',
    staff_id: 'staff-cindy',
    appointment_date: yesterdayStr,
    start_time: '11:00:00',
    end_time: '12:00:00',
    status: 'completed',
    location_type: 'salon',
    location_address: 'Via Francana 10, Pavia (Italie)',
    notes: 'Soin botox réussi. Cheveux ultra brillants.',
    confirmation_sent: true,
    reminder_sent: true,
    reminder_scheduled_at: null,
    created_at: format(subDays(new Date(), 5), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(new Date(), 1), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[7],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[5],
  },
  {
    id: 'app-6',
    client_id: 'client-1',
    service_id: 'srv-braid-2',
    staff_id: 'staff-cindy',
    appointment_date: lastWeekStr,
    start_time: '16:00:00',
    end_time: '17:45:00',
    status: 'completed',
    location_type: 'salon',
    location_address: 'Via Francana 10, Pavia (Italie)',
    notes: 'Stitch braids régulières.',
    confirmation_sent: true,
    reminder_sent: true,
    reminder_scheduled_at: null,
    created_at: format(subDays(new Date(), 10), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(new Date(), 7), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[1],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[0],
  },
  {
    id: 'app-7',
    client_id: 'client-5',
    service_id: 'srv-6',
    staff_id: 'staff-cindy',
    appointment_date: twoWeeksAgoStr,
    start_time: '14:30:00',
    end_time: '15:15:00',
    status: 'completed',
    location_type: 'home',
    location_address: 'Viale Libertà 15, Pavia (Italie)',
    notes: 'Coupe et taille de barbe avec serviette chaude.',
    confirmation_sent: true,
    reminder_sent: true,
    reminder_scheduled_at: null,
    created_at: format(subDays(new Date(), 18), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(new Date(), 14), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[5],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[4],
  },
  {
    id: 'app-8',
    client_id: 'client-3',
    service_id: 'srv-braid-1',
    staff_id: 'staff-cindy',
    appointment_date: subDays(new Date(), 4).toISOString().split('T')[0],
    start_time: '10:00:00',
    end_time: '12:30:00',
    status: 'cancelled',
    location_type: 'salon',
    location_address: 'Via Francana 10, Pavia (Italie)',
    notes: '[Annulé : Empêchement professionnel client]',
    confirmation_sent: true,
    reminder_sent: true,
    reminder_scheduled_at: null,
    created_at: format(subDays(new Date(), 8), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    updated_at: format(subDays(new Date(), 4), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    services: MOCK_SERVICES[0],
    staff: MOCK_STAFF[0],
    profiles: MOCK_CLIENTS[2],
  },
];

// 5. REWARDS MOCK
export const MOCK_REWARDS: Reward[] = [
  {
    id: 'rew-1',
    name: 'Soin hydratant express offert',
    description: 'Un soin réparateur express aux huiles végétales offert lors de votre prochain rendez-vous.',
    points_required: 50,
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'rew-2',
    name: 'Remise immédiate de 10 €',
    description: 'Bénéficiez de 10 € de déduction sur la prestation ou le modèle de tresse de votre choix.',
    points_required: 100,
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'rew-3',
    name: 'Shampoing traitant & Brushing Offert',
    description: 'Un rituel de lavage et brushing éclat offert en studio ou à domicile.',
    points_required: 150,
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'rew-4',
    name: 'Prestation complète offerte',
    description: 'Votre coupe, coiffure tressée ou soin botox entièrement offert.',
    points_required: 250,
    is_active: true,
    created_at: '2026-01-01T10:00:00Z',
  },
];

// 6. LOYALTY TRANSACTIONS MOCK
export const MOCK_LOYALTY_TRANSACTIONS: (LoyaltyTransaction & { profiles?: Profile })[] = [
  {
    id: 'tx-1',
    client_id: 'client-2',
    points: 95,
    transaction_type: 'earned',
    appointment_id: 'app-2',
    description: 'Points gagnés : Knotless braids (95 €)',
    created_at: format(subDays(new Date(), 2), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    profiles: MOCK_CLIENTS[1],
  },
  {
    id: 'tx-2',
    client_id: 'client-6',
    points: 55,
    transaction_type: 'earned',
    appointment_id: 'app-5',
    description: 'Points gagnés : Soin Botox Capillaire & Massage (55 €)',
    created_at: format(subDays(new Date(), 3), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    profiles: MOCK_CLIENTS[5],
  },
  {
    id: 'tx-3',
    client_id: 'client-1',
    points: 60,
    transaction_type: 'earned',
    appointment_id: 'app-6',
    description: 'Points gagnés : Stitch braids (60 €)',
    created_at: format(subDays(new Date(), 7), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    profiles: MOCK_CLIENTS[0],
  },
  {
    id: 'tx-4',
    client_id: 'client-2',
    points: -100,
    transaction_type: 'redeemed',
    appointment_id: null,
    description: 'Récompense échangée : Remise immédiate de 10 €',
    created_at: format(subDays(new Date(), 12), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    profiles: MOCK_CLIENTS[1],
  },
  {
    id: 'tx-5',
    client_id: 'client-6',
    points: 50,
    transaction_type: 'earned',
    appointment_id: null,
    description: 'Bonus de fidélité VIP : Parrainage cliente satisfaite',
    created_at: format(subDays(new Date(), 15), "yyyy-MM-dd'T'HH:mm:ss'Z'"),
    profiles: MOCK_CLIENTS[5],
  },
];

// 7. AVAILABILITY SETTINGS MOCK
export const MOCK_AVAILABILITY: AvailabilitySetting[] = [
  { id: 'av-1', day_of_week: 1, start_time: '09:00:00', end_time: '19:00:00', is_active: true }, // Lundi
  { id: 'av-2', day_of_week: 2, start_time: '09:00:00', end_time: '19:00:00', is_active: true }, // Mardi
  { id: 'av-3', day_of_week: 3, start_time: '09:00:00', end_time: '19:00:00', is_active: true }, // Mercredi
  { id: 'av-4', day_of_week: 4, start_time: '09:00:00', end_time: '19:00:00', is_active: true }, // Jeudi
  { id: 'av-5', day_of_week: 5, start_time: '09:00:00', end_time: '19:00:00', is_active: true }, // Vendredi
  { id: 'av-6', day_of_week: 6, start_time: '09:00:00', end_time: '18:00:00', is_active: true }, // Samedi
  { id: 'av-0', day_of_week: 0, start_time: '10:00:00', end_time: '14:00:00', is_active: false }, // Dimanche
];

// 8. BLOCKED DATES MOCK
export const MOCK_BLOCKED_DATES: BlockedDate[] = [
  {
    id: 'blk-1',
    date: format(addDays(new Date(), 14), 'yyyy-MM-dd'),
    reason: 'Formation Masterclass Braids & Tresses Artistiques',
    is_full_day: true,
    created_at: '2026-01-01T10:00:00Z',
  },
  {
    id: 'blk-2',
    date: format(addDays(new Date(), 21), 'yyyy-MM-dd'),
    reason: 'Jour férié (Festa Nazionale)',
    is_full_day: true,
    created_at: '2026-01-01T10:00:00Z',
  },
];
