name: CI & Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --include=optional

      - name: Run Unit Tests
        run: npm run test

      - name: Build Project
        run: npm run build
        env:
          VITE_SUPABASE_URL: "https://tnjaovxgfusliistcxcz.supabase.co"
          VITE_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuamFvdnhnZnVzbGlpc3RjeGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3OTUyOTIsImV4cCI6MjEwMzM3MTI5Mn0.8JpY50jUV1QLifzw6CGB0NLqydbDK1ZE0jhR1KT9ZmQ"
